<div class="Responsive">
  <div class="banner">
    <div class="js-carousel carousel">
      <div class="js-carouselCtx carousel-content">
        <div class="js-carouselList carousel-content-list">
          <div class="carousel-content-list-item" id="carousel1" data-index="1">
            <img src="\top\img\carousel_001.webp" alt="carousel001">
          </div>
          <div class="carousel-content-list-item" id="carousel2" data-index="2">
            <img src="\top\img\carousel_002.webp" alt="carousel001">
          </div>
          <div class="carousel-content-list-item" id="carousel3" data-index="3">
            <img src="\top\img\carousel_003.webp" alt="carousel001">
          </div>
          <div class="carousel-content-list-item" id="carousel4" data-index="4">
            <img src="\top\img\carousel_004.webp" alt="carousel001">
          </div>
          <div class="carousel-content-list-item" id="carousel5" data-index="5">
            <img src="\top\img\carousel_006.webp" alt="carousel001">
          </div>
          <div class="carousel-content-list-item" id="carousel6" data-index="6">
            <img src="\top\img\carousel_006.webp" alt="carousel001">
          </div>
        </div>
        <div class="carousel-content__button"></div>
        <div class="carousel-content__button carousel-content__button--right"></div>
      </div>
      <div class="carousel-nav">
        <div class="js-carouselNavItem carousel-nav-item carousel-nav-item--active" data-index="1">
          <p class="only-pc carousel-nav-item__txt">1</p>
        </div>
        <div class="js-carouselNavItem carousel-nav-item" data-index="2">
          <p class="only-pc  carousel-nav-item__txt">2</p>
        </div>
        <div class="js-carouselNavItem carousel-nav-item" data-index="3">
          <p class="only-pc  carousel-nav-item__txt">3</p>
        </div>
        <div class="js-carouselNavItem carousel-nav-item" data-index="4">
          <p class="only-pc  carousel-nav-item__txt">4</p>
        </div>
        <div class="js-carouselNavItem carousel-nav-item" data-index="5">
          <p class="only-pc  carousel-nav-item__txt">5</p>
        </div>
        <div class="js-carouselNavItem carousel-nav-item" data-index="6">
          <p class="only-pc  carousel-nav-item__txt">6</p>
        </div>
      </div>
    </div>
    <div class="banner-content">
      <a href="#" class="banner-content__item">
        <img src="\top\img\banner_item_01.webp" alt="">
      </a>
      <a href="#" class="banner-content__item">
        <img src="\top\img\banner_item_02.webp.png" alt="">
      </a>
    </div>
  </div>
</div>
